### ISSUE TITLE
Include new arff parser

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#116]

**Comment by rvraghav93** [comment]
Ping myself

Links - 

The draft of the new cythonized arff parser with automatic Categorical Encoding - https://gist.github.com/rvraghav93/9fa3166d64b196d40b68

**Todo**

- [ ] Enable sparse support
- [ ] Enable conversion without encoding too (using numpy's struct definitions)
- [ ] Make all the tests pass

**Comment by mfeurer** [comment]
@raghavrv could you please post the link to your arff parser here so we don't forget where it is?

**Comment by mfeurer** [comment]
Sadly, this will most likely not happen any more.

Closing this for now as @jnothman is constantly improving liac-arff.
